import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#fcf9f8',
  },
  topBar: {
    height: 78,
    paddingTop: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f8f4f2',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 196, 174, 0.25)',
  },
  topLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  brand: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1c1b1b',
    letterSpacing: -0.25,
  },
  brandAccent: {
    color: '#c9920a',
  },
  avatarBubble: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ffdea6',
    borderWidth: 1,
    borderColor: '#f9bc3d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#271900',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 104,
  },
  greetingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 22,
  },
  greetingTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1c1b1b',
    letterSpacing: -0.2,
  },
  greetingSubtitle: {
    marginTop: 2,
    fontSize: 14,
    fontWeight: '600',
    color: '#504534',
  },
  datePill: {
    marginTop: 4,
    backgroundColor: 'rgba(255, 222, 166, 0.35)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.5)',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  dateText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#271900',
  },
  heroCard: {
    position: 'relative',
    minHeight: 176,
    borderRadius: 18,
    padding: 20,
    justifyContent: 'space-between',
    overflow: 'hidden',
    backgroundColor: '#8e6200',
    shadowColor: '#c9920a',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 4,
  },
  heroBubble: {
    position: 'absolute',
    width: 160,
    height: 160,
    right: -36,
    top: -42,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  heroBody: {
    maxWidth: '88%',
  },
  heroTitle: {
    color: '#ffffff',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '800',
  },
  heroSubtitle: {
    marginTop: 6,
    color: 'rgba(255,255,255,0.86)',
    fontSize: 14,
    fontWeight: '500',
  },
  heroButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
  },
  heroButtonText: {
    color: '#7c5800',
    fontWeight: '800',
    fontSize: 14,
  },
  indicatorRow: {
    marginTop: 14,
    marginBottom: 22,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  indicatorActive: {
    width: 20,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#c9920a',
  },
  indicatorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(212, 196, 174, 0.7)',
  },
  sectionHeader: {
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1c1b1b',
  },
  sectionLink: {
    color: '#c9920a',
    fontWeight: '700',
    fontSize: 14,
  },
  activityList: {
    gap: 10,
  },
  activityCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.3)',
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  activityMain: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  activityIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  activityIconPrimary: { backgroundColor: 'rgba(255, 222, 166, 0.35)' },
  activityIconSecondary: { backgroundColor: 'rgba(255, 188, 54, 0.2)' },
  activityIconNeutral: { backgroundColor: '#eae7e7' },
  activityText: { flex: 1 },
  activityTitle: {
    color: '#1c1b1b',
    fontSize: 14,
    fontWeight: '800',
  },
  activitySubtitle: {
    color: '#504534',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  activityTime: {
    marginTop: 4,
    color: '#827562',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  tag: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginLeft: 10,
  },
  tagPrimary: { backgroundColor: 'rgba(255, 222, 166, 0.45)' },
  tagSecondary: { backgroundColor: 'rgba(255, 188, 54, 0.28)' },
  tagNeutral: { backgroundColor: 'rgba(229, 226, 225, 0.9)' },
  tagText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#271900',
  },
  statsRow: {
    marginTop: 18,
    gap: 10,
    flexDirection: 'row',
  },
  statCard: {
    flex: 1,
    backgroundColor: '#f6f3f2',
    borderRadius: 16,
    padding: 16,
    minHeight: 132,
    justifyContent: 'space-between',
  },
  statValue: {
    marginTop: 10,
    fontSize: 30,
    fontWeight: '900',
    color: '#1c1b1b',
  },
  statLabel: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: '800',
    color: '#827562',
    textTransform: 'uppercase',
  },
  footer: {
    marginTop: 26,
    alignItems: 'center',
  },
  footerLinks: {
    flexDirection: 'row',
    gap: 14,
  },
  footerLink: {
    fontSize: 11,
    fontWeight: '800',
    color: '#c9920a',
  },
  footerCopy: {
    marginTop: 8,
    fontSize: 10,
    color: '#504534',
    opacity: 0.6,
  },
  footerVersion: {
    marginTop: 2,
    fontSize: 9,
    color: '#504534',
    opacity: 0.6,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#8e6200',
    shadowColor: '#c9920a',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    elevation: 4,
  },
  fabBadge: {
    position: 'absolute',
    right: -2,
    top: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#ba1a1a',
    borderWidth: 2,
    borderColor: '#fcf9f8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
  },
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    flexDirection: 'row',
  },
  drawerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(28,27,27,0.2)',
  },
  drawerPanel: {
    width: 270,
    backgroundColor: '#ffffff',
    paddingTop: 24,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 18,
    marginTop: 4,
  },
  drawerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 222, 166, 0.28)',
    borderWidth: 1,
    borderColor: '#f9bc3d',
  },
  drawerAvatarText: {
    fontWeight: '800',
    fontSize: 14,
    color: '#271900',
  },
  drawerName: {
    color: '#1c1b1b',
    fontWeight: '800',
    fontSize: 16,
  },
  drawerRole: {
    color: '#504534',
    fontSize: 12,
  },
  drawerNav: {
    gap: 6,
  },
  drawerItem: {
    height: 46,
    borderRadius: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  drawerItemText: {
    color: '#504534',
    fontWeight: '600',
    fontSize: 14,
  },
  drawerItemActive: {
    backgroundColor: 'rgba(255, 222, 166, 0.38)',
    borderLeftWidth: 4,
    borderLeftColor: '#7c5800',
  },
  drawerItemActiveText: {
    color: '#271900',
    fontWeight: '800',
    fontSize: 14,
  },
  drawerLogout: {
    marginTop: 'auto',
    height: 46,
    borderRadius: 12,
    backgroundColor: 'rgba(186, 26, 26, 0.06)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  drawerLogoutText: {
    color: '#ba1a1a',
    fontWeight: '800',
    fontSize: 14,
  },
});

export default styles;
