import { StyleSheet } from 'react-native';

export function createDashboardStyles(c) {
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: c.background },
    topBar: {
      paddingBottom: 14,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: c.topBar,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    topLeft: { flexDirection: 'row', alignItems: 'center' },
    brand: { fontSize: 22, fontWeight: '800', color: c.text, letterSpacing: -0.25 },
    brandAccent: { color: c.brandAccent },
    avatarBubble: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: c.avatarBg,
      borderWidth: 1,
      borderColor: c.avatarBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: { fontSize: 12, fontWeight: '800', color: c.avatarText },
    content: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 104 },
    greetingTitle: { fontSize: 28, fontWeight: '800', color: c.text, letterSpacing: -0.2 },
    greetingSubtitle: { marginTop: 2, fontSize: 14, fontWeight: '600', color: c.textSecondary },
    datePill: {
      marginTop: 4,
      backgroundColor: c.pillBg,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.border,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    dateText: { fontSize: 11, fontWeight: '700', color: c.avatarText },
    heroCard: {
      position: 'relative',
      minHeight: 176,
      borderRadius: 18,
      padding: 20,
      justifyContent: 'space-between',
      overflow: 'hidden',
      backgroundColor: '#8e6200',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.24,
      shadowRadius: 18,
      elevation: 4,
    },
    heroBubble: {
      position: 'absolute',
      width: 160,
      height: 160,
      right: -36,
      top: -42,
      borderRadius: 80,
      backgroundColor: c.heroOverlay,
    },
    heroBody: { maxWidth: '88%' },
    heroTitle: { color: '#ffffff', fontSize: 22, lineHeight: 28, fontWeight: '800' },
    heroSubtitle: { marginTop: 6, color: 'rgba(255,255,255,0.86)', fontSize: 14, fontWeight: '500' },
    heroButton: {
      alignSelf: 'flex-start',
      backgroundColor: '#ffffff',
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 12,
    },
    heroButtonText: { color: c.primaryDark, fontWeight: '800', fontSize: 14 },
    indicatorRow: {
      marginTop: 14,
      marginBottom: 22,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 6,
    },
    indicatorActive: { width: 20, height: 6, borderRadius: 999, backgroundColor: c.primary },
    indicatorDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.border },
    sectionTitle: { fontSize: 22, fontWeight: '800', color: c.text },
    sectionLink: { color: c.primary, fontWeight: '700', fontSize: 14 },
    activityList: { gap: 10 },
    activityCard: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 16,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    activityMain: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    activityIconBox: {
      width: 48,
      height: 48,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    activityIconPrimary: { backgroundColor: c.pillBg },
    activityIconSecondary: { backgroundColor: c.decor },
    activityIconNeutral: { backgroundColor: c.cardAlt },
    activityText: { flex: 1 },
    activityTitle: { color: c.text, fontSize: 14, fontWeight: '800' },
    activitySubtitle: { color: c.textSecondary, fontSize: 12, fontWeight: '600', marginTop: 2 },
    activityTime: {
      marginTop: 4,
      color: c.textMuted,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0.35,
      textTransform: 'uppercase',
    },
    tag: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5, marginLeft: 10 },
    tagPrimary: { backgroundColor: c.pillBg },
    tagSecondary: { backgroundColor: c.decor },
    tagNeutral: { backgroundColor: c.cardAlt },
    tagText: { fontSize: 10, fontWeight: '800', color: c.avatarText },
    statsRow: { marginTop: 18, gap: 10, flexDirection: 'row' },
    statCard: {
      flex: 1,
      backgroundColor: c.cardAlt,
      borderRadius: 16,
      padding: 16,
      minHeight: 132,
      justifyContent: 'space-between',
    },
    statValue: { marginTop: 10, fontSize: 30, fontWeight: '900', color: c.text },
    statLabel: {
      marginTop: 4,
      fontSize: 11,
      fontWeight: '800',
      color: c.textMuted,
      textTransform: 'uppercase',
    },
    footerLink: { fontSize: 11, fontWeight: '800', color: c.primary },
    footerCopy: { marginTop: 8, fontSize: 10, color: c.textSecondary, opacity: 0.6 },
    footerVersion: {
      marginTop: 2,
      fontSize: 9,
      color: c.textSecondary,
      opacity: 0.6,
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    fab: {
      position: 'absolute',
      right: 24,
      bottom: 88,
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#8e6200',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 14,
      elevation: 4,
    },
    fabBadge: {
      position: 'absolute',
      right: -2,
      top: -2,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: '#ba1a1a',
      borderWidth: 2,
      borderColor: c.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    fabBadgeText: { color: '#ffffff', fontSize: 10, fontWeight: '800' },
    greetingRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 22,
    },
    sectionHeader: {
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    footer: { marginTop: 26, alignItems: 'center' },
    footerLinks: { flexDirection: 'row', gap: 14 },
  });
}
