import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#fcf9f8',
  },
  decorTop: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(201, 146, 10, 0.06)',
    zIndex: 0,
  },
  decorBottom: {
    position: 'absolute',
    bottom: -20,
    left: -40,
    width: 256,
    height: 256,
    borderRadius: 128,
    backgroundColor: 'rgba(0, 96, 168, 0.05)',
    zIndex: 0,
  },
  topBar: {
    paddingBottom: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(252, 249, 248, 0.88)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 196, 174, 0.2)',
    zIndex: 2,
  },
  topLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brand: {
    marginLeft: 4,
    fontSize: 20,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: -0.5,
  },
  brandAccent: {
    marginLeft: 4,
    fontSize: 20,
    fontWeight: '800',
    color: '#c9920a',
    letterSpacing: -0.5,
  },
  avatarGold: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#c9920a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  avatarGoldText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 120,
    maxWidth: 430,
    alignSelf: 'center',
    width: '100%',
    zIndex: 1,
  },
  headerPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.12)',
    marginBottom: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 2,
  },
  headerPillTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: -0.3,
  },
  tableCard: {
    backgroundColor: '#ffffff',
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.12)',
    overflow: 'hidden',
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 32,
    elevation: 4,
  },
  tableHeadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(246, 243, 242, 0.65)',
    paddingVertical: 18,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 196, 174, 0.08)',
  },
  th: {
    fontSize: 10,
    fontWeight: '800',
    color: '#827562',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  thName: { flex: 1.35, paddingLeft: 4 },
  thDate: { width: 76 },
  thStatus: { width: 92, textAlign: 'center' },
  thActions: { width: 44, textAlign: 'right' },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 196, 174, 0.08)',
  },
  cellName: {
    flex: 1.35,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 4,
    minWidth: 0,
  },
  fileName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1a1a1a',
    flex: 1,
  },
  cellDate: {
    width: 76,
    fontSize: 11,
    fontWeight: '600',
    color: '#504534',
  },
  cellStatus: {
    width: 92,
    alignItems: 'center',
  },
  cellActions: {
    width: 44,
    alignItems: 'flex-end',
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    maxWidth: 92,
  },
  badgeText: {
    fontSize: 9,
    fontWeight: '800',
    textAlign: 'center',
  },
  badgeAvailable: { backgroundColor: '#dcfce7' },
  badgeAvailableText: { color: '#15803d' },
  badgeProcess: { backgroundColor: '#ffedd5' },
  badgeProcessText: { color: '#c2410c' },
  badgeQueued: { backgroundColor: '#dbeafe' },
  badgeQueuedText: { color: '#1d4ed8' },
  badgeError: { backgroundColor: '#fee2e2' },
  badgeErrorText: { color: '#b91c1c' },
  paginationBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: 'rgba(246, 243, 242, 0.45)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(212, 196, 174, 0.12)',
  },
  paginationLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#504534',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  paginationBtns: {
    flexDirection: 'row',
    gap: 8,
  },
  pageBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageBtnDisabled: {
    opacity: 0.35,
  },
  statsTitle: {
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 2,
  },
  statsTitleText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  statsTitleBar: {
    width: 8,
    height: 20,
    borderRadius: 4,
    backgroundColor: '#c9920a',
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 14,
    marginBottom: 20,
  },
  metricCard: {
    width: '48%',
    backgroundColor: '#ffffff',
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.12)',
    padding: 22,
    overflow: 'hidden',
    minHeight: 120,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.03,
    shadowRadius: 24,
    elevation: 2,
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#827562',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  metricValue: {
    fontSize: 30,
    fontWeight: '900',
    color: '#1a1a1a',
    letterSpacing: -1,
  },
  metricValueAccent: {
    fontSize: 30,
    fontWeight: '900',
    color: '#c9920a',
    letterSpacing: -1,
  },
  metricIconBg: {
    position: 'absolute',
    right: -8,
    bottom: -8,
    opacity: 0.06,
  },
  chartCard: {
    backgroundColor: '#ffffff',
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.12)',
    padding: 22,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.03,
    shadowRadius: 24,
    elevation: 2,
  },
  chartHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  chartHeadTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  chartHeadTotal: {
    fontSize: 10,
    fontWeight: '800',
    color: '#827562',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  barTrack: {
    height: 16,
    borderRadius: 999,
    backgroundColor: '#f6f3f2',
    flexDirection: 'row',
    overflow: 'hidden',
    marginBottom: 16,
  },
  barSeg1: { flex: 60, backgroundColor: '#c9920a' },
  barSeg2: { flex: 25, backgroundColor: '#5a9fed' },
  barSeg3: { flex: 15, backgroundColor: '#fbbc36' },
  legendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    rowGap: 10,
    paddingTop: 4,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#504534',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  footer: {
    paddingTop: 28,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(212, 196, 174, 0.15)',
    alignItems: 'center',
  },
  footerCopy: {
    fontSize: 10,
    fontWeight: '800',
    color: '#827562',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 88,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#c9920a',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 60,
    flexDirection: 'row',
  },
  drawerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(28,27,27,0.2)',
  },
  drawerPanel: {
    width: 270,
    backgroundColor: '#ffffff',
    paddingTop: 24,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 18,
    marginTop: 4,
  },
  drawerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 222, 166, 0.28)',
    borderWidth: 1,
    borderColor: '#f9bc3d',
  },
  drawerAvatarText: {
    fontWeight: '800',
    fontSize: 14,
    color: '#271900',
  },
  drawerName: {
    color: '#1c1b1b',
    fontWeight: '800',
    fontSize: 16,
  },
  drawerRole: {
    color: '#504534',
    fontSize: 12,
  },
  drawerNav: {
    gap: 6,
  },
  drawerItem: {
    height: 46,
    borderRadius: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  drawerItemText: {
    color: '#504534',
    fontWeight: '600',
    fontSize: 14,
  },
  drawerItemActive: {
    backgroundColor: 'rgba(255, 222, 166, 0.38)',
    borderLeftWidth: 4,
    borderLeftColor: '#7c5800',
  },
  drawerItemActiveText: {
    color: '#271900',
    fontWeight: '800',
    fontSize: 14,
  },
  drawerLogout: {
    marginTop: 'auto',
    height: 46,
    borderRadius: 12,
    backgroundColor: 'rgba(186, 26, 26, 0.06)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  drawerLogoutText: {
    color: '#ba1a1a',
    fontWeight: '800',
    fontSize: 14,
  },
});

export default styles;
