import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#fcf9f8',
  },
  topBar: {
    paddingBottom: 14,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(252, 249, 248, 0.92)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(201, 146, 10, 0.12)',
    shadowColor: '#c9920a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    zIndex: 4,
  },
  topLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  menuBtn: {
    padding: 8,
    borderRadius: 12,
  },
  topTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#7c5800',
    letterSpacing: -0.3,
  },
  topAvatarWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#7c5800',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  topAvatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 140,
    maxWidth: 520,
    alignSelf: 'center',
    width: '100%',
  },
  capsule: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f6f3f2',
    paddingHorizontal: 22,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.15)',
    marginBottom: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  capsuleDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#c9920a',
  },
  capsuleText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#7c5800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 28,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.12)',
    shadowColor: '#7c5800',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 6,
  },
  cardDecor: {
    position: 'absolute',
    top: -48,
    right: -48,
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: 'rgba(124, 88, 0, 0.06)',
  },
  avatarSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarRing: {
    width: 92,
    height: 92,
    borderRadius: 46,
    padding: 3,
    marginBottom: 4,
  },
  avatarInner: {
    flex: 1,
    borderRadius: 43,
    backgroundColor: '#ffffff',
    padding: 2,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
  },
  avatarPlaceholder: {
    flex: 1,
    borderRadius: 40,
    backgroundColor: '#eae7e7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholderText: {
    fontSize: 28,
    fontWeight: '800',
    color: '#7c5800',
  },
  editPhotoBtn: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#7c5800',
    borderWidth: 4,
    borderColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  displayName: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1c1b1b',
    marginBottom: 22,
    textAlign: 'center',
  },
  fields: {
    gap: 14,
    marginBottom: 22,
  },
  fieldLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#827562',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginLeft: 4,
  },
  fieldBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    backgroundColor: 'rgba(234, 231, 231, 0.45)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  fieldBoxEditing: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(212, 196, 174, 0.35)',
  },
  fieldText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#1c1b1b',
  },
  fieldInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#1c1b1b',
    padding: 0,
    margin: 0,
  },
  primaryBtn: {
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#7c5800',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 6,
  },
  primaryBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  primaryBtnText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  secondaryBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f6f3f2',
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.35)',
  },
  secondaryBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#504534',
  },
  footer: {
    marginTop: 36,
    paddingTop: 28,
    paddingBottom: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(212, 196, 174, 0.2)',
    alignItems: 'center',
    gap: 8,
  },
  footerBrand: {
    fontSize: 14,
    fontWeight: '800',
    color: '#7c5800',
  },
  footerTag: {
    fontSize: 12,
    fontWeight: '600',
    color: '#827562',
    marginBottom: 12,
  },
  footerLinks: {
    flexDirection: 'row',
    gap: 22,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  footerLink: {
    fontSize: 12,
    fontWeight: '800',
    color: '#504534',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 88,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#7c5800',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
    shadowColor: '#7c5800',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
});

export default styles;
