import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#fcf9f8',
  },
  topBar: {
    height: 78,
    paddingTop: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(252, 249, 248, 0.92)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 196, 174, 0.25)',
  },
  topLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  brand: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1c1b1b',
    letterSpacing: -0.25,
  },
  brandAccent: {
    color: '#c9920a',
  },
  avatarBubble: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ffdea6',
    borderWidth: 1,
    borderColor: '#f9bc3d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#271900',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 120,
  },
  heroSection: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.2)',
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    overflow: 'hidden',
  },
  heroKicker: {
    fontSize: 10,
    fontWeight: '800',
    color: '#c9920a',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1c1b1b',
    lineHeight: 28,
    marginBottom: 6,
  },
  heroSubtitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#504534',
    maxWidth: 280,
    lineHeight: 18,
  },
  heroIconWrap: {
    position: 'absolute',
    right: -8,
    top: '25%',
    opacity: 0.06,
  },
  gridCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.15)',
    padding: 16,
    shadowColor: '#1c1b1b',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  gridIconBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#fff9eb',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  gridCardTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1c1b1b',
    marginBottom: 4,
  },
  gridCardDesc: {
    fontSize: 12,
    fontWeight: '600',
    color: '#504534',
    lineHeight: 16,
    minHeight: 32,
  },
  gridUseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    gap: 4,
  },
  gridUseText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#c9920a',
  },
  eduSection: {
    marginBottom: 24,
  },
  eduCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.15)',
    padding: 24,
    alignItems: 'center',
    shadowColor: '#1c1b1b',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  eduTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1c1b1b',
    textAlign: 'center',
  },
  eduBody: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: '500',
    color: '#504534',
    textAlign: 'center',
    lineHeight: 22,
  },
  eduImage: {
    width: '100%',
    height: 160,
    borderRadius: 16,
    marginTop: 24,
    backgroundColor: '#eae7e7',
  },
  dotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    marginTop: 16,
  },
  dotActive: {
    width: 20,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#c9920a',
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(212, 196, 174, 0.45)',
  },
  footer: {
    paddingTop: 28,
    borderTopWidth: 1,
    borderTopColor: 'rgba(212, 196, 174, 0.2)',
    alignItems: 'center',
    gap: 10,
  },
  footerLinks: {
    flexDirection: 'row',
    gap: 16,
  },
  footerLink: {
    fontSize: 10,
    fontWeight: '700',
    color: '#504534',
    opacity: 0.75,
  },
  footerCopy: {
    fontSize: 10,
    fontWeight: '600',
    color: '#504534',
    opacity: 0.55,
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#c9920a',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 6,
  },
  fabBadge: {
    position: 'absolute',
    right: -2,
    top: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#ba1a1a',
    borderWidth: 2,
    borderColor: '#fcf9f8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
  },
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    flexDirection: 'row',
  },
  drawerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(28,27,27,0.2)',
  },
  drawerPanel: {
    width: 270,
    backgroundColor: '#ffffff',
    paddingTop: 24,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 18,
    marginTop: 4,
  },
  drawerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 222, 166, 0.28)',
    borderWidth: 1,
    borderColor: '#f9bc3d',
  },
  drawerAvatarText: {
    fontWeight: '800',
    fontSize: 14,
    color: '#271900',
  },
  drawerName: {
    color: '#1c1b1b',
    fontWeight: '800',
    fontSize: 16,
  },
  drawerRole: {
    color: '#504534',
    fontSize: 12,
  },
  drawerNav: {
    gap: 6,
  },
  drawerItem: {
    height: 46,
    borderRadius: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  drawerItemText: {
    color: '#504534',
    fontWeight: '600',
    fontSize: 14,
  },
  drawerItemActive: {
    backgroundColor: 'rgba(255, 222, 166, 0.38)',
    borderLeftWidth: 4,
    borderLeftColor: '#7c5800',
  },
  drawerItemActiveText: {
    color: '#271900',
    fontWeight: '800',
    fontSize: 14,
  },
  drawerLogout: {
    marginTop: 'auto',
    height: 46,
    borderRadius: 12,
    backgroundColor: 'rgba(186, 26, 26, 0.06)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  drawerLogoutText: {
    color: '#ba1a1a',
    fontWeight: '800',
    fontSize: 14,
  },
});

export default styles;
