import { StyleSheet } from 'react-native';

export function createSettingsStyles(c) {
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: c.background },
    topBar: {
      paddingBottom: 14,
      paddingHorizontal: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: c.topBar,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      zIndex: 4,
    },
    topLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    brand: { fontSize: 20, fontWeight: '800', color: c.primaryDark, letterSpacing: -0.4 },
    avatarRing: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: c.card,
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    avatarText: { fontSize: 13, fontWeight: '800', color: c.avatarText },
    content: {
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 120,
      maxWidth: 560,
      alignSelf: 'center',
      width: '100%',
    },
    headerPill: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: c.cardAlt,
      paddingHorizontal: 22,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.borderLight,
      marginBottom: 26,
    },
    headerPillText: { fontSize: 13, fontWeight: '800', color: c.primaryDark, letterSpacing: 0.3 },
    mainCard: {
      backgroundColor: c.card,
      borderRadius: 20,
      overflow: 'hidden',
      marginBottom: 22,
      borderWidth: 1,
      borderColor: c.borderLight,
      shadowColor: c.primaryDark,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.06,
      shadowRadius: 24,
      elevation: 4,
    },
    rowBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 22,
    },
    rowLeft: { flexDirection: 'row', alignItems: 'center', gap: 16, flex: 1, paddingRight: 12 },
    rowIconBox: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: c.decor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    rowTitle: { fontSize: 16, fontWeight: '800', color: c.text },
    rowSubtitle: { fontSize: 13, fontWeight: '600', color: c.textSecondary, marginTop: 4 },
    sectionLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: c.textMuted,
      letterSpacing: 2,
      textTransform: 'uppercase',
      marginLeft: 14,
      marginBottom: 14,
      marginTop: 6,
    },
    toggleCard: {
      backgroundColor: c.card,
      borderRadius: 18,
      padding: 18,
      marginBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: c.borderLight,
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
      elevation: 1,
    },
    toggleLeft: { flexDirection: 'row', alignItems: 'center', gap: 14, flex: 1, paddingRight: 12 },
    toggleLabel: { fontSize: 16, fontWeight: '700', color: c.text },
    logoutBtn: {
      marginTop: 36,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      alignSelf: 'center',
      paddingVertical: 8,
    },
    logoutText: { fontSize: 14, fontWeight: '800', color: '#ba1a1a' },
    footer: { marginTop: 28, alignItems: 'center', gap: 6 },
    footerVer: { fontSize: 12, fontWeight: '600', color: c.textMuted },
    footerCopy: { fontSize: 12, fontWeight: '600', color: c.textMuted, textAlign: 'center', opacity: 0.8 },
    fab: {
      position: 'absolute',
      right: 28,
      bottom: 92,
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 70,
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 10,
    },
  });
}
