import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#fcf9f8',
  },
  topBar: {
    height: 78,
    paddingTop: 18,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(252, 249, 248, 0.95)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 196, 174, 0.2)',
    zIndex: 4,
  },
  topLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  menuBtn: {
    padding: 8,
    borderRadius: 999,
  },
  brand: {
    fontSize: 20,
    fontWeight: '800',
    color: '#7c5800',
    letterSpacing: -0.4,
  },
  avatarRing: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#c9920a',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  avatarText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#453000',
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 120,
    maxWidth: 560,
    alignSelf: 'center',
    width: '100%',
  },
  headerPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f6f3f2',
    paddingHorizontal: 22,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.2)',
    marginBottom: 26,
  },
  headerPillText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#7c5800',
    letterSpacing: 0.3,
  },
  mainCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 22,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.12)',
    shadowColor: '#7c5800',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 24,
    elevation: 4,
  },
  rowBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 22,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flex: 1,
    paddingRight: 12,
  },
  rowIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(124, 88, 0, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1c1b1b',
  },
  rowSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#504534',
    marginTop: 4,
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#827562',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginLeft: 14,
    marginBottom: 14,
    marginTop: 6,
  },
  toggleCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 18,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(246, 243, 242, 0.8)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  toggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flex: 1,
    paddingRight: 12,
  },
  toggleLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1c1b1b',
  },
  logoutBtn: {
    marginTop: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'center',
    paddingVertical: 8,
  },
  logoutText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#ba1a1a',
  },
  footer: {
    marginTop: 28,
    alignItems: 'center',
    gap: 6,
  },
  footerVer: {
    fontSize: 12,
    fontWeight: '600',
    color: '#827562',
  },
  footerCopy: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(130, 117, 98, 0.65)',
    textAlign: 'center',
  },
  fab: {
    position: 'absolute',
    right: 28,
    bottom: 28,
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 70,
    shadowColor: '#c9920a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
});

export default styles;
