import { StyleSheet } from 'react-native';

/** Colores alineados al mockup Tailwind (stt-accent, superficies M3). */
export const C = {
  bg: '#fcf9f8',
  sttAccent: '#3B82F6',
  sttAccentDark: '#1d4ed8',
  onSurface: '#1c1b1b',
  onSurfaceVariant: '#504534',
  outline: '#827562',
  outlineVariant: '#d4c4ae',
  primary: '#7c5800',
  primaryContainer: '#c9920a',
  surfaceLow: '#f6f3f2',
  surfaceHigh: '#eae7e7',
  surfaceBright: '#fcf9f8',
  white: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  error: '#ba1a1a',
};

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: C.bg,
  },
  bgGlow: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    overflow: 'hidden',
  },
  glowBlob1: {
    position: 'absolute',
    top: '18%',
    left: -80,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(249, 188, 54, 0.12)',
  },
  glowBlob2: {
    position: 'absolute',
    bottom: '22%',
    right: -80,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
  },
  header: {
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 22,
    minHeight: 64,
    backgroundColor: C.bg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(212, 196, 174, 0.35)',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: C.primary,
    letterSpacing: -0.3,
  },
  micBadge: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: {
    paddingHorizontal: 22,
    paddingTop: 16,
    paddingBottom: 120,
    zIndex: 1,
  },
  hero: {
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 32,
    minHeight: 228,
    paddingHorizontal: 28,
    paddingVertical: 32,
    justifyContent: 'center',
  },
  heroBubble: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(255,255,255,0.1)',
    right: -56,
    bottom: -56,
  },
  heroIconBg: {
    position: 'absolute',
    right: 20,
    top: 36,
    opacity: 0.2,
  },
  heroTextBlock: {
    maxWidth: 400,
    zIndex: 2,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginBottom: 14,
  },
  heroBadgeText: {
    color: C.white,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2,
  },
  heroTitle: {
    color: C.white,
    fontSize: 36,
    fontWeight: '800',
    lineHeight: 42,
    marginBottom: 12,
    maxWidth: 340,
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 17,
    lineHeight: 26,
    maxWidth: 360,
    fontWeight: '500',
  },
  sectionLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: C.outline,
    textTransform: 'uppercase',
  },
  sectionLine: {
    flex: 1,
    height: 2,
    marginLeft: 12,
    backgroundColor: 'rgba(212, 196, 174, 0.35)',
  },
  cardsCol: {
    gap: 22,
  },
  card: {
    backgroundColor: C.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.15)',
    padding: 24,
    shadowColor: '#c9920a',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 28,
    elevation: 4,
  },
  helpBtn: {
    position: 'absolute',
    top: 14,
    right: 14,
    padding: 6,
    zIndex: 1,
  },
  cardIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  cardIconBoxBlue: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
  },
  cardIconBoxGold: {
    backgroundColor: 'rgba(201, 146, 10, 0.12)',
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 6,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: C.onSurface,
  },
  limitPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: C.errorContainer,
  },
  limitPillText: {
    fontSize: 10,
    fontWeight: '800',
    color: C.onErrorContainer,
  },
  fileTypes: {
    fontSize: 10,
    fontWeight: '800',
    color: C.outlineVariant,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  cardBody: {
    fontSize: 14,
    color: C.onSurfaceVariant,
    lineHeight: 22,
    marginBottom: 16,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 18,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: C.surfaceLow,
  },
  chipText: {
    fontSize: 11,
    fontWeight: '700',
    color: C.outline,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  langGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  langCell: {
    flex: 1,
    backgroundColor: C.surfaceLow,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.15)',
  },
  langLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: C.outline,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  langValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  langValue: {
    fontSize: 12,
    fontWeight: '800',
    color: C.onSurface,
  },
  primaryBtn: {
    marginTop: 4,
    backgroundColor: C.sttAccent,
    borderRadius: 14,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryBtnText: {
    color: C.white,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  fab: {
    position: 'absolute',
    right: 22,
    bottom: 28,
    width: 60,
    height: 60,
    borderRadius: 30,
    zIndex: 60,
    shadowColor: C.sttAccent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
  recentSection: {
    marginTop: 40,
  },
  recentTitle: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: C.outline,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  recentStack: {
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(212, 196, 174, 0.2)',
  },
  recentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 18,
    backgroundColor: C.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(212, 196, 174, 0.25)',
  },
  recentItemFirst: {
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  recentItemLast: {
    borderBottomWidth: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  recentLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 14,
  },
  recentIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.surfaceHigh,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentName: {
    fontSize: 14,
    fontWeight: '800',
    color: C.onSurface,
  },
  recentMeta: {
    fontSize: 11,
    color: C.outline,
    marginTop: 2,
  },
});

export default styles;
