import { StyleSheet } from 'react-native';

export function createSpeechToTextStyles(c, darkMode) {
  const sttAccent = '#3B82F6';
  const sttAccentDark = '#1d4ed8';

  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: c.background, overflow: 'hidden' },
    modalRoot: { flex: 1, justifyContent: 'flex-end' },
    backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: darkMode ? 'rgba(0,0,0,0.65)' : 'rgba(28,27,27,0.45)' },
    sheet: {
      width: '100%',
      flexGrow: 1,
      maxHeight: '96%',
      backgroundColor: c.background,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      overflow: 'hidden',
      borderTopWidth: StyleSheet.hairlineWidth,
      borderLeftWidth: StyleSheet.hairlineWidth,
      borderRightWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: 0,
      borderColor: c.borderLight,
    },
    sheetScroll: { flexGrow: 1 },
    bgGlow: { ...StyleSheet.absoluteFillObject, zIndex: 0, overflow: 'hidden' },
    glowBlob1: {
      position: 'absolute',
      top: '12%',
      left: -80,
      width: 220,
      height: 220,
      borderRadius: 110,
      backgroundColor: darkMode ? 'rgba(201, 146, 10, 0.08)' : 'rgba(249, 188, 54, 0.12)',
    },
    glowBlob2: {
      position: 'absolute',
      bottom: '18%',
      right: -80,
      width: 220,
      height: 220,
      borderRadius: 110,
      backgroundColor: darkMode ? 'rgba(59, 130, 246, 0.1)' : 'rgba(59, 130, 246, 0.08)',
    },
    header: {
      zIndex: 2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 14,
      backgroundColor: c.topBar,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
    iconBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: darkMode ? c.cardAlt : 'transparent',
    },
    headerTitle: { fontSize: 18, fontWeight: '800', color: c.primaryDark, letterSpacing: -0.3 },
    micBadge: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: darkMode ? 'rgba(59, 130, 246, 0.18)' : 'rgba(59, 130, 246, 0.1)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    scroll: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 28, zIndex: 1 },
    hero: {
      borderRadius: 12,
      overflow: 'hidden',
      marginBottom: 20,
      minHeight: 160,
      paddingHorizontal: 22,
      paddingVertical: 24,
      justifyContent: 'center',
    },
    heroBubble: {
      position: 'absolute',
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: 'rgba(255,255,255,0.1)',
      right: -48,
      bottom: -48,
    },
    heroIconBg: { position: 'absolute', right: 16, top: 24, opacity: 0.2 },
    heroTextBlock: { maxWidth: '85%', zIndex: 2 },
    heroBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: 'rgba(255,255,255,0.2)',
      marginBottom: 10,
    },
    heroBadgeText: { color: '#fff', fontSize: 9, fontWeight: '800', letterSpacing: 1.5 },
    heroTitle: { color: '#fff', fontSize: 26, fontWeight: '800', lineHeight: 32, marginBottom: 8 },
    heroSubtitle: { color: 'rgba(255,255,255,0.85)', fontSize: 14, lineHeight: 21, fontWeight: '500' },
    tabsRow: {
      flexDirection: 'row',
      backgroundColor: c.cardAlt,
      borderRadius: 14,
      padding: 4,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: c.borderLight,
    },
    tabBtn: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 6,
    },
    tabBtnActive: { backgroundColor: c.card, shadowColor: c.shadow, shadowOpacity: 0.08, shadowRadius: 6, elevation: 2 },
    tabText: { fontSize: 13, fontWeight: '700', color: c.textMuted },
    tabTextActive: { color: c.text, fontWeight: '800' },
    sectionLabelRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    sectionLabel: {
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.2,
      color: c.textMuted,
      textTransform: 'uppercase',
    },
    sectionLine: { flex: 1, height: 2, marginLeft: 10, backgroundColor: c.border },
    card: {
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.borderLight,
      padding: 20,
      marginBottom: 16,
    },
    helpBtn: { position: 'absolute', top: 12, right: 12, padding: 6, zIndex: 1 },
    cardIconBox: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 14,
      backgroundColor: darkMode ? 'rgba(59, 130, 246, 0.18)' : 'rgba(59, 130, 246, 0.1)',
    },
    cardTitleRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8, marginBottom: 6 },
    cardTitle: { fontSize: 17, fontWeight: '800', color: c.text },
    limitPill: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 4,
      backgroundColor: darkMode ? 'rgba(186, 26, 26, 0.2)' : '#ffdad6',
    },
    limitPillText: { fontSize: 10, fontWeight: '800', color: darkMode ? '#fca5a5' : '#93000a' },
    fileTypes: {
      fontSize: 10,
      fontWeight: '800',
      color: c.textMuted,
      letterSpacing: 1,
      textTransform: 'uppercase',
      marginBottom: 10,
    },
    cardBody: { fontSize: 13, color: c.textSecondary, lineHeight: 20, marginBottom: 14 },
    chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
    chip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999, backgroundColor: c.cardAlt },
    chipText: {
      fontSize: 10,
      fontWeight: '700',
      color: c.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    primaryBtn: {
      marginTop: 4,
      backgroundColor: sttAccent,
      borderRadius: 14,
      paddingVertical: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    primaryBtnText: { color: '#fff', fontSize: 14, fontWeight: '800' },
    recentSection: { marginTop: 8 },
    recentTitle: {
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.2,
      color: c.textMuted,
      textTransform: 'uppercase',
      marginBottom: 10,
    },
    recentStack: { borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: c.borderLight },
    recentItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 14,
      backgroundColor: c.card,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.borderLight,
    },
    recentItemLast: { borderBottomWidth: 0 },
    recentLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 12 },
    recentIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: c.cardAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recentName: { fontSize: 13, fontWeight: '800', color: c.text },
    recentMeta: { fontSize: 10, color: c.textMuted, marginTop: 2 },
    handleBar: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: c.border,
      marginTop: 10,
      marginBottom: 4,
    },
  });
}

export const STT_GRADIENT = ['#3B82F6', '#1d4ed8'];
